version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - my_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    restart: always
    command: >
      sh -c "sleep 5 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

volumes:
  my_db:
