version: "3.9"
services:
  db:
    image: "postgres:15"
    environment:
      POSTGRES_DB: "DB"
      POSTGRES_USER: "USER"
      POSTGRES_PASSWORD: "PASSWORD"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "USER", "-d", "DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "/app/entrypoint.sh"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data:
